### PR TITLE
Initial Release of Money Tally Application

### PR DESCRIPTION
**Pull request by lily4178993**
### Pull Request Overview
I am thrilled to announce the initial release of the "Money Tally" application. This Rails application is designed for straightforward tracking and monitoring of daily expenses.

#### Introduction to Money Tally
Money Tally is a user-friendly application aimed at simplifying financial management. It allows users to:

- **Create and Confirm Accounts**: Register and verify accounts via email.
- **Authenticate**: Secure user login.
- **Expense Tracking**: Log daily expenses in user-defined categories.
- **Monthly Expense Overview**: View categorized monthly spending.
- **Profile Management**: Edit personal information.

#### Key Features
1. **Secure Registration and Authentication**
2. **Customizable Expense Categories**
3. **Intuitive Expense Logging**
4. **Detailed Monthly Summaries**
5. **User Profile Customization**

#### Purpose and Goals
The primary goal of Money Tally is to offer a simple yet effective tool for managing personal finances. This release is the foundation, providing essential features for efficient expense tracking.

#### Testing and Quality Assurance
- Comprehensive testing has been conducted to ensure functionality and reliability.
- Automated tests cover key features to maintain high code quality.
- **Test Suite Video**: For a visual confirmation of our rigorous testing process, please view this short video showing all tests passing successfully: [Link to Video](https://drive.google.com/file/d/1ryIdNdABpO9HR2QvNfoU86HysbpxS07C/view?usp=sharing)

#### Demo
- [Walkthrough Video Presentation](https://drive.google.com/file/d/1ZJwOaMegnjA6zFliJln9v8TGjeYo_sOD/view?usp=sharing)

---

This release is just the beginning for Money Tally. We eagerly await feedback and contributions from the community to further enhance this personal finance management tool. Thank you for your support!

### CODE REVIEW

**Review by Olamarx — CHANGES_REQUESTED** [review]
Hi @lily4178993, 

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
- Linters passed ✔️
- Beautiful aesthetics ✔️
- Gitflow ✔️
- All test cases passed ✔️
- Well deployed ✔️

## Required Changes ♻️
_Check the comments under the review._
- [ ] You probably forgot to give credit to the designer of the project template you used in your acknowledgement. This is part of the requirement to use the design and even a requirement for this project.
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Olamarx** [comment]
@lily4178993 I think you made changes to your readme and it is now not professional, I picked the link to your live demo and video from your readme and now I cant find it. Kindly add them all as they were and also the acknowledgement.

**Comment by lily4178993** [comment]
I did not make any changes

**Comment by Olamarx** [comment]
> I did not make any changes
> 
> Here is the acknowledgement section image

Yes, that is what is supposed to be there but it was not there before plus, is that what you have in your repo currently? because what I can see here is the image below
image

**Comment by lily4178993** [comment]
There is a problem with Github. The readme exist in the project source but can not be seen. I will try to add it manually

**Comment by Olamarx** [comment]
> There is a problem with Github. The readme exist in the project source but can not be seen. I will try to add it manually

Oh, that's a glitch from Github then, let me know how it goes though.

**Comment by lily4178993** [comment]
Hi @Olamarx, can you help me? I can't resolve the problem

**Comment by Olamarx** [comment]
Let me take a second look.

**Comment by Olamarx** [comment]
@lily4178993 I will advice you make the submission, I just confirmed that it appears to be a general issue from GitHub because another project has similar issue, the next reviewer should be able to approve it for you.

**Comment by lily4178993** [comment]
@Olamarx, it's solved. I just make the feat branch as default in order to make the readme file appear

**Comment by Olamarx** [comment]
Good job!!!

**Review by Olamarx — APPROVED** [review]
Hi @lily4178993, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Changes fixed ✔️
- Readme file professional ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by lily4178993** [comment]
Thank you for the approval!

**Pull request merged**
